name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx

      - name: Build API image
        run: docker build -t kira-api:latest -f api/Dockerfile .

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve

      - name: Wait for API
        run: |
          for i in {1..30}; do
            curl -fsS http://localhost:8000/healthz && exit 0 || sleep 2
          done
          exit 1

      - name: Post-deploy tests (required by assignment)
        run: |
          pytest -q

      - name: Export basic DORA metrics (artifact)
        run: |
          echo "deploy_time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> dora.txt
          echo "commit_sha=${{ github.sha }}" >> dora.txt
          echo "workflow_run_id=${{ github.run_id }}" >> dora.txt

      - name: Upload DORA artifact
        uses: actions/upload-artifact@v4
        with:
          name: dora-metrics
          path: dora.txt

      - name: Terraform Destroy (cleanup)
        if: always()
        working-directory: infra/terraform
        run: terraform destroy -auto-approve

